root = "."
tmp_dir = "tmp"

[build]
  # 指定构建命令，使用 /cmd/server/main.go
  cmd = "go build -o ./tmp/main ./cmd/server/main.go"
  # 指定二进制文件路径
  bin = "./tmp/main"
  include = []
  exclude = []

[watch]
  dir = "."
  include = ["*.go"]
  exclude = []
  delay = "100ms"

[log]
  time = true
  color = true